[package]
name = "novuskinc"
version = "0.1.0"
authors = ["The New Kernel developers"]
edition = "2018"
description = "Most of novuskinc from Novusk, used for making userspace applications"

[dependencies]
cfg-if = "1.0.0"
